# homebrew packages utils
#
# ansible-playbook 01_utils_osx.yml (--tags=brew or --skip-tags=brew,cask)

---

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    HOMEBREW_TAPS:
      - homebrew/cask-drivers

    HOMEBREW_CASK_PACKAGES:
      - docker

    HOMEBREW_PACKAGES:
      - { name: awscli }
      - { name: htop-osx }
      - { name: jq }
      - { name: bash }
      - { name: gnu-sed }
      - { name: vim }
      - { name: gnu-tar }
      - { name: tldr }
      - { name: findutils }
      - { name: fzf }

    export_paths:
      - GNUTAR="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
      - BASH="/usr/local/bin:$PATH"
      - GNUSED="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

  tasks:

    - name: install taps of homebrew
      homebrew_tap:
        tap: "{{ item }}"
        state: present
      with_items: "{{ HOMEBREW_TAPS }}"
      tags:
        - cask

    - name: update homebrew
      homebrew:
        update_homebrew: yes
      tags:
        - brew
        - cask

    - name: install homebrew cask packages
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items: "{{ HOMEBREW_CASK_PACKAGES }}"
      ignore_errors: true
      tags:
        - cask

    - name: install homebrew packages
      homebrew:
        name: "{{ item.name }}"
        state: "{{ item.state|default('latest') }}"
        install_options: "{{ item.install_options|default() }}"
      with_items: "{{ HOMEBREW_PACKAGES }}"
      tags:
        - brew

    - name: add path bashrc
      lineinfile:
        path: "~/.bashrc"
        line: "export {{ item }}"
      with_items: "{{ export_paths }}"
      failed_when: false
      tags:
        - brew

    - name: add path zshrc
      lineinfile:
        path: "~/.zshrc"
        line: "export {{ item }}"
      with_items: "{{ export_paths }}"
      failed_when: false
      tags:
        - brew

    - name: reset ssh connection
      meta: reset_connection
      tags:
        - brew
        - cask
