# install deno
#
# ansible-playbook 15_deno.yml

---

- hosts: localhost

  tasks:

  - name: install deno
    homebrew:
      name: "deno"
      update_homebrew: yes
      state: present
    connection: local

  - name: reset ssh connection
    meta: reset_connection