# install rust
#
# ansible-playbook 30_rust.yml --extra-vars "USER=$(whoami)"

---

- hosts: localhost

  vars:
    FILE: "rust.sh"
    HOME: "Users/{{ USER }}"
    DEST: "{{ CACHE_DIR }}/{{ FILE }}"

  tasks:

    - include_tasks: inc/cache.yml

    - name: download installer
      get_url:
        url: https://sh.rustup.rs
        dest: "{{ DEST }}"
        mode: 0755
      register: installer

    - name: install rust
      command: "{{ DEST }} -y"
      changed_when: installer.changed == true

    - name: set path variable
      lineinfile:
        path: "~/{{ item }}"
        line: "export PATH=\"{{ HOME }}/.cargo/bin:$PATH\""
      with_items:
        - .bashrc
        - .zshrc
      connection: local

    - name: reset ssh connection
      meta: reset_connection
