# install rust
#
# ansible-playbook 30_rust.yml --extra-vars "USER=$(whoami)"

---

- hosts: localhost

  vars:
    FILE: "rust.sh"
    HOME: "Users/{{ USER }}"
    DEST: "{{ CACHE_DIR }}/{{ FILE }}"

  tasks:
    - name: install rust
      homebrew:
        name: "rust"
        update_homebrew: yes
        state: present
      connection: local

    - name: set path variable
      lineinfile:
        path: "~/{{ item }}"
        line: "export PATH=\"{{ HOME }}/.cargo/bin:$PATH\""
      with_items:
        - .bashrc
        - .zshrc
      connection: local
      failed_when: false

    - name: reset ssh connection
      meta: reset_connection
