# install visual studio code
#
# ansible-playbook 40_vscode.yml

---

- hosts: localhost
  connection: local

  tasks:

    - name: update homebrew
      homebrew:
        update_homebrew: yes

    - name: install visual studio code
      homebrew_cask:
        name: visual-studio-code
        state: present

    - name: install plugins
      command: "code --install-extension {{ item }}"
      with_items:
        - vscoss.vscode-ansible
        - ms-vscode.go
        - davidanson.vscode-markdownlint
        - shd101wyy.markdown-preview-enhanced
        - ms-python.python
        - eriklynd.json-tools