# install kotlin
#
# ansible-playbook 50_kotlin.yml

---

- hosts: localhost

  tasks:

    - name: install kotlin
      homebrew:
        name: "kotlin"
        update_homebrew: yes
        state: present
      connection: local

