# install scala
#
# ansible-playbook 60_scala.yml

---

- hosts: localhost

  tasks:

    - name: install scala
      homebrew:
        name: "scala"
        update_homebrew: yes
        state: present
      connection: local