name: Ansible-lint

on:
  push:
    branches:
      - master

jobs:

  builds:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
         python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Lint playbook
        run: |
          ansible-playbook 00_ssh.yml --syntax-check
          ansible-lint 00_ssh.yml
