name: Ansible-lint-ubunut

on:
  push:
    branches:
      - master

jobs:

  builds:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint playbooks
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            00_ssh.yml
          override-deps: |
            ansible==2.8
